In [ ]:
import numpy as np

In [ ]:
#1
a=np.arange(1,10).reshape(3,3)
b=np.array_split(a,3)
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [ ]:
#2
a=np.arange(1,9).reshape(2,2,-1)
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#3
m=np.array([[[1,2,3],[4,5,6],[7,8,9],[0,1,2]]])
l=np.array([[[5,6,7],[8,9,4],[8,3,5],[3,6,7]]])
n=np.concatenate((m,l),axis=1)
o=np.concatenate((m,l),axis=2)
print(n)
print(o)

[[[1 2 3]
  [4 5 6]
  [7 8 9]
  [0 1 2]
  [5 6 7]
  [8 9 4]
  [8 3 5]
  [3 6 7]]]
[[[1 2 3 5 6 7]
  [4 5 6 8 9 4]
  [7 8 9 8 3 5]
  [0 1 2 3 6 7]]]


In [ ]:
#4
a=np.array(['apple','banana','cherry','date','elderberry','fry'])
b=np.array(['a','e','i','o','u'])
c=[]
for i in a:
    for j in i:
        if j in b:
         if i not in c:
            c.append(i)
print(np.array(c))

['apple', 'banana', 'cherry', 'date', 'elderberry']


In [ ]:
#5
a=np.array([9,10,20,30,40,33,50])
b=[True,False,False,True,False,True,False]
a[b]

array([ 9, 30, 33])

In [ ]:
#6
a=np.array(([1.1,1.2,1.3]),dtype=int)
print(a)

[1 1 1]


In [ ]:
#7
p = np.zeros((5,5),dtype=int)
for i in range(5):
  p[i,i] = 1
print(p)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
#8
x=np.array([[1,2],[4,6],[8,9],[2,2]])
y=np.array([[3,5],[5,7],[9,6],[9,4]])
print(x*y)

[[ 3 10]
 [20 42]
 [72 54]
 [18  8]]


In [ ]:
#9
a = np.array([[[5, 6, 7, 8], [6, 8, 9, 0]], [[6, 4, 7, 0], [3, 2, 1, 5]]])
for i in range(a.shape[0]):
  for x in range(a.shape[1]):
    for y in range(a.shape[2]):
      print("Index: ", (i, x, y), "Value: ", a[i][x][y])

Index:  (0, 0, 0) Value:  5
Index:  (0, 0, 1) Value:  6
Index:  (0, 0, 2) Value:  7
Index:  (0, 0, 3) Value:  8
Index:  (0, 1, 0) Value:  6
Index:  (0, 1, 1) Value:  8
Index:  (0, 1, 2) Value:  9
Index:  (0, 1, 3) Value:  0
Index:  (1, 0, 0) Value:  6
Index:  (1, 0, 1) Value:  4
Index:  (1, 0, 2) Value:  7
Index:  (1, 0, 3) Value:  0
Index:  (1, 1, 0) Value:  3
Index:  (1, 1, 1) Value:  2
Index:  (1, 1, 2) Value:  1
Index:  (1, 1, 3) Value:  5


In [ ]:
#10
x=np.arange(26)
x[x%5==0]='5'
x[x%3==0]='3'
print(x)

[ 5  1  2  3  4  5  3  7  8  3  5 11  3 13 14  5 16 17  3 19  5  3 22 23
  3  5]


In [ ]:
#11
x=np.array([[5,6,2,7,8,9],[1,7,8,10,11,8]])
y=np.sort(x)
print(np.searchsorted(x[0],8,side="right"))
print(np.searchsorted(x[1],8,side="right"))

5
3
